/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.wblei.plugin

import com.android.build.gradle.AppExtension
import groovy.lang.Closure
import org.gradle.api.Project
import org.gradle.api.Plugin
import java.lang.IllegalArgumentException

/**
 * A simple 'hello world' plugin.
 */
class MjpoetPlugin: Plugin<Project> {
    override fun apply(project: Project) {
        var android = project.extensions.getByType(AppExtension::class.java)
        android ?: throw IllegalArgumentException("The plugin can only used in android project.")
        
        // create the an extension for plugin.
        val mjpoetConfig = project.extensions.create("mjpoet", MjpoetConfig::class.java)
        project.afterEvaluate {
            android.applicationVariants.all {
                val mjpoet = project.extensions.getByName("mjpoet") as MjpoetConfig
                if (it.name in mjpoet.variants) {
    
                    print("hello wrold......\n")
//                print((mjpoet.mjconfig?: error("no config for release")).call().packageBase)
                    println(mjpoet.packageBase)
                    println(it.name)
                }
            }
        }
    }
}
